name: Build Godot Project (Release)

on:
  workflow_dispatch: {}
  release:
    types: [created]

jobs:
  export:
    runs-on: ubuntu-latest

    # Godot CI image with templates available
    container:
      image: barichello/godot-ci:4.6

    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: LinuxDesktop
            out: build/linux/jigsaw.x86_64
            artifact: Client-linux
          - preset: LinuxServer
            out: build/server/jigsaw_server.x86_64
            artifact: Server-linux
          - preset: Windows
            out: build/windows/jigsaw.exe
            artifact: Client-windows
          - preset: macOS
            out: build/mac/jigsaw.zip
            artifact: Client-mac

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
       
      - name: Install export dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig1

      - name: Make output folders
        run: |
          mkdir -p build/linux build/server build/windows build/mac

      # Release export (change to --export-debug if you want debug builds)
      - name: Export
        run: |
          godot --headless --verbose --export-release "${{ matrix.preset }}" "${{ matrix.out }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.out }}
